<!DOCTYPE html>
<!-- 
<html lang="pt-BR">

   <head>
      <meta charset="UTF-8">
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>
         <x?php echo $cedente; ?>
      </title>
      <style type="text/css">
      /* Embed the CSS content here */
      <x?php include $resource_path . '/css/styles.css'?>
      </style>
   </head>
   <body>  
-->
      <div style="width: 863px">
<!--     
         <div style="float: left">
            <table class="table-boleto" style="width: 180px" cellpadding="0" cellspacing="0" border="0">
               <tr>
                  <td>
                     <div class="titulo">Vencimento</div>
                     <div class="conteudo">
                        <?php echo $data_vencimento ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">Agência/Código do Beneficiário</div>
                     <div class="conteudo">
                        <?php echo $agencia_codigo_cedente ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">Nosso número</div>
                     <div class="conteudo">
                        <?php echo $nosso_numero ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">Nº documento</div>
                     <div class="conteudo">
                        <?php echo $numero_documento ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">Espécie</div>
                     <div class="conteudo">
                        <?php echo $especie ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">Quantidade</div>
                     <div class="conteudo">
                        <?php echo $quantidade ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">(=) Valor Documento</div>
                     <div class="conteudo">
                        <?php echo $valor_documento ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">(-) Descontos / Abatimentos</div>
                     <div class="conteudo">
                        <?php echo $desconto_abatimento ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">(-) Outras deduções</div>
                     <div class="conteudo">
                        <?php echo $outras_deducoes ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">(+) Mora / Multa</div>
                     <div class="conteudo">
                        <?php echo $mora_multa ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td>
                     <div class="titulo">(+) Outros acréscimos</div>
                     <div class="conteudo">
                        <?php echo $outros_acrescimos ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td class="bottomborder">
                     <div class="titulo">(=) Valor cobrado</div>
                     <div class="conteudo">
                        <?php echo $valor_cobrado ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td class="bottomborder">
                     <div class="titulo">CNPJ do Beneficiário</div>
                     <div class="conteudo">
                        <?php echo $cedente_cpf_cnpj ?>
                     </div>
                  </td>
               </tr>
               <tr>
                  <td class="bottomborder">
                     <div class="titulo">Endereço do Beneficiário</div>
                     <div class="conteudo">
                        <?php echo $cedente_endereco1 ?>
                     </div>
                  </td>
               </tr>
            </table>
            <span class="header">Recibo do Pagador</span>
         </div>
         !-->         
         <div style="float: left; margin-left: 1px">
            <!-- Ficha de compensação -->
            <?php include ('partials/ficha-de-compensacao.phtml') ?>
         </div>
         <div style="clear: both"></div>
         <div class="linha-pontilhada">Corte na linha pontilhada</div>
      </div>
<!--
   </body>

</html>

-->